### ISSUE TITLE
Home Assistant is not updating

### ISSUE THREAD

**Issue by eeezyy** [ronschaeffer/sbm2mqtt#13]
I am having issues connecting Home Assistant to MQTT.

Here's my `configuration.yaml`
```
mqtt:
  client_id: home_assistant
  broker: 193.168.178.39
  port: 8123
  username: admin
  password: password
  discovery: true
  birth_message:
    topic: 'home-assistant/status'
    payload: 'online'
  will_message:
    topic: 'home-assistant/status'
    payload: 'offline'

sensor:
- platform: mqtt
  name: 'switchbot_meter_temperature'
  state_topic: 'switchbot_meter/<the-mac-address-from-output>' # MAC address of this meter
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C' # Change to '°F' as appropriate
- platform: mqtt
  name: 'switchbot_meter_humidity'
  state_topic: 'switchbot_meter/<the-mac-address-from-output>' # MAC address of this meter
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: '%'
  icon: mdi:water-percent
- platform: mqtt
  name: 'switchbot_meter_battery'
  state_topic: 'switchbot_meter/<the-mac-address-from-output>' # MAC address of this meter
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
  icon: mdi:battery
```

I see that Home assistant is connected to the MQTT Broker, to be sure I set the client_id.

I also have the MQTT Integration Plugin installed (I think this is needed).

On the card in the dashboard the values stay at "Unknown".

What am I doing wrong? Is there a step I'm missing?
Don't have experience using MQTT yet (using HiveMQ Broker at the moment).
