### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by GreenBear33** [ronschaeffer/sbm2mqtt#3]
Hi, I am trying to set this up but I am not able to get it to work. I am running a raspberry pi 3 with a fresh install of Raspbian. I have Docker and have 3 working containers (Python, Nodered and Homeassistant). I would like to run this repeatedly in the container and update Home assistant with the temperature and humidity + battery readings. 

I am facing problems after following all the instructions. 

I have created the directory called switchbot and added both files to it. 

I adjusted the details in the config file to my own.

I try to run the module in python to test it but I get the following: 

Traceback (most recent call last):
  File "/home/pi/switchbot/sbm2mqtt.py", line 18, in <module>
    from sbm2mqtt_config import (
  File "/home/pi/switchbot/sbm2mqtt_config.py", line 7
    mqtt_host = 192.168.1.158
                        ^
SyntaxError: invalid syntax
>>> 

I am running Mosquitto broker on the pi itself.

**Comment by ronschaeffer** [comment]
Try with the IP address of the MQTT broker in quotes like this:

`mqtt_host = "xxx.xxx.xxx.xxx"`

**Comment by GreenBear33** [comment]
Hi Ron, Thanks. That worked, kind of...

Now I am getting the following message when running it?

Scanning for SwitchBot Meters...
Traceback (most recent call last):
  File "/home/pi/switchbot/sbm2mqtt.py", line 115, in <module>
    main()
  File "/home/pi/switchbot/sbm2mqtt.py", line 109, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)
>>>

**Comment by GreenBear33** [comment]
I have checked for pexpect and also run the most recent version you posted 3 hours ago. 

I hope we can get this to work.

**Comment by ronschaeffer** [comment]
Are you running with sudo?

`sudo python3 sbm2mqtt.py`

**Comment by GreenBear33** [comment]
Of course. Sorry about that. Hard to keep up when I'm learning at every corner. 

It is working, when I run it I can find both my sensors. Now I am struggling trying to edit the configuration.yaml file because I am using the docker image and not Hass.io. 

Also in the editing of the etc/crontab, do I just add the lines anywhere at the bottom of that file?

I appreciate any help you can give. Many thanks.

**Comment by ronschaeffer** [comment]
> Of course. Sorry about that. Hard to keep up when I'm learning at every corner.
> 
> It is working, when I run it I can find both my sensors. Now I am struggling trying to edit the configuration.yaml file because I am using the docker image and not Hass.io.

Glad you got it working. If you have a 

Without knowing more about your set up, it's hard to advise on editing configuration.yaml. DO you have an item called Editor in the left sidebar menu in Home Assistant? If so, look there. If you don't asking for advice here https://community.home-assistant.io/ which a detailed description of your set up. 

> 
> Also in the editing of the etc/crontab, do I just add the lines anywhere at the bottom of that file?
> 

Yes.

> I appreciate any help you can give. Many thanks.

No problem.

**Comment by GreenBear33** [comment]
Hi Ron, 

Thanks again for the help. I managed to edit the configuration.yaml file and edit etc/crontab. 

I am however getting the following error in Home assistant: Invalid Config:

![image](https://user-images.githubusercontent.com/65681255/82587305-d1762c00-9b90-11ea-9a66-e09a6db158b7.png)

Any ideas?

**Comment by GreenBear33** [comment]
Hi Ron,

Sorry for the above. i relaised it was my fault as I hadn't added the mqtt broker to the configuration.yaml file. 

I have managed to get it working .... well partly. I can only get one of my sensors to show up as you can see below. 

![image](https://user-images.githubusercontent.com/65681255/82590795-37b17d80-9b96-11ea-9a5a-4f19b0b41f5c.png)

I am going to tinker a bit more but hopefully you have an easy solution for this final step as I am almost there.

**Comment by GreenBear33** [comment]
It seems to have only found the lower sensor but the upper sensor is not found. I have checked the code and they are identical. Is there any reason for this?

I read the README again and you mention a split configuration and to use sensors.yaml. But I don't really understand what you mean and whether it applies here.

**Comment by ronschaeffer** [comment]
Can you post the relevant mqtt: and sensor: sections of your
configuration.yaml?

Are you able to see the sbm2mqtt MQTT messages, for example with an MQTT on
your phone?

**Comment by GreenBear33** [comment]
Please see the relevant configuration.yaml sections below.

mqtt:
  broker: 192.168.1.158
  
sensor:
- platform: mqtt
  name: 'Upper Sensor'
  state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C' # Change to '°F' as appropriate
- platform: mqtt
  name: 'Upper Sensor'
  state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: '%'
  icon: mdi:water-percent
- platform: mqtt
  name: 'Upper Sensor'
  state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
  icon: mdi:battery
  
sensor:
- platform: mqtt
  name: 'Lower Sensor'
  state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C' # Change to '°F' as appropriate
- platform: mqtt
  name: 'Lower Sensor'
  state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: '%'
  icon: mdi:water-percent
- platform: mqtt
  name: 'Lower Sensor'
  state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
  icon: mdi:battery

As mentioned above, Only one of the sensors is working, but the code seems to be identical.

**Comment by ronschaeffer** [comment]
It's much easier to diagnose if you format the section from configuration.yaml as code in your message. Simply paste the section in, select all of it, and click the icon that looks like <> in the toolbar above your message. Indentation and spacing is very important in YAML. You lose that in the message without proper formatting.

> 
> sensor:
> 
> * platform: mqtt
>   name: 'Upper Sensor'
>   state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
>   value_template: '{{ value_json.temperature }}'
>   unit_of_measurement: '°C' # Change to '°F' as appropriate
> * platform: mqtt
>   name: 'Upper Sensor'
>   state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
>   value_template: '{{ value_json.humidity }}'
>   unit_of_measurement: '%'
>   icon: mdi:water-percent
> * platform: mqtt
>   name: 'Upper Sensor'
>   state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
>   value_template: '{{ value_json.battery }}'
>   unit_of_measurement: '%'
>   icon: mdi:battery
> 
> sensor:
> 
> * platform: mqtt
>   name: 'Lower Sensor'
>   state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
>   value_template: '{{ value_json.temperature }}'
>   unit_of_measurement: '°C' # Change to '°F' as appropriate
> * platform: mqtt
>   name: 'Lower Sensor'
>   state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
>   value_template: '{{ value_json.humidity }}'
>   unit_of_measurement: '%'
>   icon: mdi:water-percent
> * platform: mqtt
>   name: 'Lower Sensor'
>   state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
>   value_template: '{{ value_json.battery }}'
>   unit_of_measurement: '%'
>   icon: mdi:battery
> 

Does this not give you an error if you go to Configuration (in the sidebar) / Server Controls and then "Configuration validation"? You shouldn't repeat  `sensor:` .

Try this instead:

```
sensors:
- platform: mqtt
  name: 'Upper Sensor'
  state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C' # Change to '°F' as appropriate
- platform: mqtt
  name: 'Upper Sensor'
  state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: '%'
  icon: mdi:water-percent
- platform: mqtt
  name: 'Upper Sensor'
  state_topic: 'switchbot_meter/d1:49:4a:73:93:99' # MAC address of this meter
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
  icon: mdi:battery
- platform: mqtt
  name: 'Lower Sensor'
  state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C' # Change to '°F' as appropriate
- platform: mqtt
  name: 'Lower Sensor'
  state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: '%'
  icon: mdi:water-percent
- platform: mqtt
  name: 'Lower Sensor'
  state_topic: 'switchbot_meter/d1:ee:38:10:6c:c8' # MAC address of this meter
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
  icon: mdi:battery
```
If you still don't see both Meters, there are two things that you can check:

1. Go to Configuration (in the sidebar) / Entities and look for them there. If you can, then manually add that other Meter to your Home Assistant dashboard.
2. Use an MQTT client app on your phone or another device and subscribe to the topic `switchbot_meter/#` to see if you can see messages from both. If you can, doublecheck the MAC addresses in your configuration.yaml.

BTW, the split configuration comment you mention is only relevant if you divide your configuration.yaml info up into pieces as described here https://www.home-assistant.io/docs/configuration/splitting_configuration/. It's easier to manage that way once you start to get a lot of devices set up.
